var fullName = 'Danary Gonzalez';
var isCool = false;
var totalPets = 1;
console.log('value of fullName is:', fullName);
console.log('value of isCool is:', isCool);
console.log('value of totalPets is:', totalPets);
console.log('typeof fullName:', typeof fullName);
console.log('typeof isCool:', typeof isCool);
console.log('typeof totalPets:', typeof totalPets);
var unknown = null;
console.log('value of unknown is:', unknown);
console.log('typeof unknown:', typeof unknown);
var never;
console.log('value of never is:', never);
console.log('typeof never:', never);
